### PR TITLE
Fix peer_ip

### PR DESCRIPTION
**Pull request by devnut**
This also needs to be pulled into 2.1.6 if you decide its an appropriate modificaation

### CODE REVIEW

**Comment by devnut** [comment]
See datastax support request #22410 - which we just got bit by again, hence this pull request.

Also - just FYI, based on looking at the code it appears to me that the Java driver would not manifest this issue.   It looks like it has a more robust / complete implementation

**Comment by devnut** [comment]
We are running 2.1.6 - so if you merge this please apply an appropriate fix to the 2.1.x branch too.  I could not figure out how to do that on github

**Comment by stamhankar999** [comment]
Thanks for the submission and heads-up. Rather than accept it, I'm going to look at the Java driver, talk to a few folks, and work on a comprehensive fix. I filed https://datastax-oss.atlassian.net/browse/RUBY-255 to track this.

**Comment by devnut** [comment]
Thanks so much, I agree thats a better approach.   Much appreciated!

Here's a stack trace:

```
undefined method `reverse' for nil:NilClass 
/usr/local/rvm/gems/ruby-2.1.1/gems/cassandra-driver-2.1.6/lib/cassandra/address_resolution/policies/ec2_multi_region.rb:44:in `resolve' 
/usr/local/rvm/gems/ruby-2.1.1/gems/cassandra-driver-2.1.6/lib/cassandra/cluster/control_connection.rb:706:in `peer_ip' 
/usr/local/rvm/gems/ruby-2.1.1/gems/cassandra-driver-2.1.6/lib/cassandra/cluster/control_connection.rb:517:in `block (2 levels) in refresh_hosts_async' 
/usr/local/rvm/gems/ruby-2.1.1/gems/cassandra-driver-2.1.6/lib/cassandra/cluster/control_connection.rb:516:in `each' 
/usr/local/rvm/gems/ruby-2.1.1/gems/cassandra-driver-2.1.6/lib/cassandra/cluster/control_connection.rb:516:in `block in refresh_hosts_async' 
/usr/local/rvm/gems/ruby-2.1.1/gems/ione-1.2.3/lib/ione/future.rb:391:in `call' 
/usr/local/rvm/gems/ruby-2.1.1/gems/ione-1.2.3/lib/ione/future.rb:391:in `block in map' 
/usr/local/rvm/gems/ruby-2.1.1/gems/ione-1.2.3/lib/ione/future.rb:750:in `call' 
/usr/local/rvm/gems/ruby-2.1.1/gems/ione-1.2.3/lib/ione/future.rb:750:in `call_listener' 
/usr/local/rvm/gems/ruby-2.1.1/gems/ione-1.2.3/lib/ione/future.rb:789:in `block in resolve' 
/usr/local/rvm/gems/ruby-2.1.1/gems/ione-1.2.3/lib/ione/future.rb:788:in `each' 
/usr/local/rvm/gems/ruby-2.1.1/gems/ione-1.2.3/lib/ione/future.rb:788:in `resolve' 
/usr/local/rvm/gems/ruby-2.1.1/gems/ione-1.2.3/lib/ione/future.rb:833:in `block (2 levels) in initialize' 
/usr/local/rvm/gems/ruby-2.1.1/gems/ione-1.2.3/lib/ione/future.rb:750:in `call' 
/usr/local/rvm/gems/ruby-2.1.1/gems/ione-1.2.3/lib/ione/future.rb:750:in `call_listener' 
/usr/local/rvm/gems/ruby-2.1.1/gems/ione-1.2.3/lib/ione/future.rb:789:in `block in resolve' 
/usr/local/rvm/gems/ruby-2.1.1/gems/ione-1.2.3/lib/ione/future.rb:788:in `each' 
/usr/local/rvm/gems/ruby-2.1.1/gems/ione-1.2.3/lib/ione/future.rb:788:in `resolve' 
/usr/local/rvm/gems/ruby-2.1.1/gems/ione-1.2.3/lib/ione/future.rb:391:in `block in map' 
/usr/local/rvm/gems/ruby-2.1.1/gems/ione-1.2.3/lib/ione/future.rb:750:in `call' 
/usr/local/rvm/gems/ruby-2.1.1/gems/ione-1.2.3/lib/ione/future.rb:750:in `call_listener' 
/usr/local/rvm/gems/ruby-2.1.1/gems/ione-1.2.3/lib/ione/future.rb:789:in `block in resolve' 
/usr/local/rvm/gems/ruby-2.1.1/gems/ione-1.2.3/lib/ione/future.rb:788:in `each' 
/usr/local/rvm/gems/ruby-2.1.1/gems/ione-1.2.3/lib/ione/future.rb:788:in `resolve' 
/usr/local/rvm/gems/ruby-2.1.1/gems/ione-1.2.3/lib/ione/future.rb:30:in `fulfill' 
/usr/local/rvm/gems/ruby-2.1.1/gems/cassandra-driver-2.1.6/lib/cassandra/protocol/cql_protocol_handler.rb:242:in `complete_request' 
/usr/local/rvm/gems/ruby-2.1.1/gems/cassandra-driver-2.1.6/lib/cassandra/protocol/v1.rb:155:in `actual_decode' 
/usr/local/rvm/gems/ruby-2.1.1/gems/cassandra-driver-2.1.6/lib/cassandra/protocol/v1.rb:86:in `decode_header' 
/usr/local/rvm/gems/ruby-2.1.1/gems/cassandra-driver-2.1.6/lib/cassandra/protocol/v1.rb:64:in `<<' 
/usr/local/rvm/gems/ruby-2.1.1/gems/cassandra-driver-2.1.6/lib/cassandra/protocol/cql_protocol_handler.rb:272:in `receive_data' 
/usr/local/rvm/gems/ruby-2.1.1/gems/ione-1.2.3/lib/ione/io/base_connection.rb:172:in `call' 
/usr/local/rvm/gems/ruby-2.1.1/gems/ione-1.2.3/lib/ione/io/base_connection.rb:172:in `read' 
/usr/local/rvm/gems/ruby-2.1.1/gems/ione-1.2.3/lib/ione/io/io_reactor.rb:517:in `block in tick' 
/usr/local/rvm/gems/ruby-2.1.1/gems/ione-1.2.3/lib/ione/io/io_reactor.rb:517:in `each' 
/usr/local/rvm/gems/ruby-2.1.1/gems/ione-1.2.3/lib/ione/io/io_reactor.rb:517:in `tick' 
/usr/local/rvm/gems/ruby-2.1.1/gems/ione-1.2.3/lib/ione/io/io_reactor.rb:159:in `block in start'
```

**Pull request closed without merging**
