### PR TITLE
Add FunctionCollection helper class

### PR DESCRIPTION
**Pull request by stamhankar999**
Encapsulate the hash of functions/aggregates in its own class, to hide the fact that we use a hash keyed on <func-name, arg-types>, which is an implementation detail.

### CODE REVIEW

**Comment by avalanche123** [comment]
looks good, I'd call it a `FunctionLookup` or `FunctionMap` instead of `FunctionCollection` though

**Comment by avalanche123** [comment]
@kishkaru please confirm as ok to merge in 3.0.0b

**Comment by kishkaru** [comment]
Looks good. In the future, let's avoid non-bugfix code changes after code complete.

**Comment by avalanche123** [comment]
please change the target branch to master

**Pull request closed without merging**
