### PR TITLE
[RUBY-116] fix thread leak on connection error

### PR DESCRIPTION
**Pull request by avalanche123**

### CODE REVIEW

**Comment by uhoh-itsmaciek** [comment]
I think this should fix leaking threads when the argument validation in `Cassandra#cluster` raises, but if we actually get to instantiating a driver, and only `Driver#connect` fails, I believe we'll still leak the executor that is [passed to Cluster](https://github.com/datastax/ruby-driver/blob/master/lib/cassandra/driver.rb#L63). Should `Driver#connect` rescue at the end and shut down the executor before re-raising?

**Comment by avalanche123** [comment]
both cases should be fixed, the one you're referring to is taken care of by this piece - https://github.com/datastax/ruby-driver/pull/72/files#diff-436239e83f5c144d3e5fd2c3fee0f5a7R148.
Whenever a control connection fails, we close the cluster, which shuts down the default executor as well

**Comment by uhoh-itsmaciek** [comment]
Oh, I think you're right. This should do it. Thank you.

**Comment by uhoh-itsmaciek** [comment]
FYI, I've deployed this to my test environment and no longer seem to be hitting Thread exhaustion issues (which I was seeing regularly before).

**Pull request merged**
