### PR TITLE
Documentation Update

### PR DESCRIPTION
**Pull request by kandalf**
This PR updates `README.md` to reference the `CONTRIBUTING.md` doc, and the latter to mention the posibility of collaboration through Pull Requests.

This might make it clearer for people in doubt whether Pull Requests are accepted.

### CODE REVIEW

**Comment by avalanche123** [comment]
this looks good, would you mind changing the link to CONTRIBUTING.md to absolute, to have it rendered correctly once I generate documentation, thanks!

**Comment by kandalf** [comment]
> this looks good, would you mind changing the link to CONTRIBUTING.md to absolute, to have it rendered correctly once I generate documentation, thanks!

Sure. I did it abosolute first, then changed it to be relative so it's kept within forked repos as well.
I'll change it back in a minute

**Comment by kandalf** [comment]
Done!

**Comment by avalanche123** [comment]
you rock sir, merging!

**Pull request merged**
