### PR TITLE
RUBY-292 replace failed connections to prevent ip for string errors

### PR DESCRIPTION
**Pull request by grosser**
https://datastax-oss.atlassian.net/projects/RUBY/issues/RUBY-292

```
vendor/bundle/ruby/2.3.0/gems/cassandra-driver-3.1.0/lib/cassandra/cluster/client.rb:436 in connect_to_host_with_retry
vendor/bundle/ruby/2.3.0/gems/cassandra-driver-3.1.0/lib/cassandra/cluster/client.rb:115 in block (2 levels) in connect
vendor/bundle/ruby/2.3.0/gems/cassandra-driver-3.1.0/lib/cassandra/cluster/client.rb:114 in each
vendor/bundle/ruby/2.3.0/gems/cassandra-driver-3.1.0/lib/cassandra/cluster/client.rb:114 in block in connect
vendor/bundle/ruby/2.3.0/gems/ione-1.2.4/lib/ione/future.rb:391 in block in map
vendor/bundle/ruby/2.3.0/gems/ione-1.2.4/lib/ione/future.rb:752 in call_listener
vendor/bundle/ruby/2.3.0/gems/ione-1.2.4/lib/ione/future.rb:791 in block in resolve
vendor/bundle/ruby/2.3.0/gems/ione-1.2.4/lib/ione/future.rb:790 in each
```

### CODE REVIEW

**Comment by grosser** [comment]
looks like that was not it ... still seeing the error pop up :(

**Comment by grosser** [comment]
updated with new patch ... we'll see if that works better ...

**Comment by grosser** [comment]
fyi @stamhankar999

**Comment by grosser** [comment]
deployed and confirmed working ...
the bad connection is `#<Cassandra::Protocol::CqlProtocolHandler:`

**Comment by grosser** [comment]
would be great to have unit tests for this, tried to add some, but did not get far :(

**Comment by stamhankar999** [comment]
After looking at your fix, I had some theories on reproducing the issue, but did not succeed. :(

**Comment by grosser** [comment]
locally all connections are Cassandra::Protocol::CqlProtocolHandler for me ... just did never get a failed one ...

putting a puts in the driver and doing Cassandra.cluster.connect(keyspace) triggered the code-path

**Pull request merged**
