### PR TITLE
Make the udf/uda minitests run a little faster

### PR DESCRIPTION
**Pull request by stamhankar999**
Replace static sleep 2's in UDF/UDA tests with calls to a new helper "assert_wait_and_retry_until" that tests the desired condition repeatedly until it succeeds or a timeout is hit.

### CODE REVIEW

**Comment by avalanche123** [comment]
good catch. Note there there is https://github.com/datastax/ruby-driver/blob/3.0.0b/support/retry.rb as well, maybe we could reuse it.
additionally, after thinking some more, I think we can do even better by using a schema listener avoid polling altogether

something like:

```ruby
listener = SchemaChangeListener.new
cluster.register(listener)
session.execute("CREATE AGGREGATE sum_agg(int)
                 SFUNC sum_int
                 STYPE int
                 INITCOND 0")
listener.wait_for_change('simplex') {|ks| ks.has_aggregate?("sum_agg", int)}
```

where listener could be

```ruby
class SchemaChangeListener
  class Condition
    def initialize(promise, &block)
      @promise = promise
      @block   = block
    end

    def evaluate(keyspace)
      @promise.fulfill if @block.call(keyspace)
    rescue => e
      @promise.break(e)
    end
  end

  def initialize
    @conditions = {}
  end

  def wait_for_change(keyspace_name, timeout = nil, &block)
    promise = Cassandra::Future.promise
    @conditions[keyspace_name] ||= []
    @conditions[keyspace_name] << Condition.new(promise, &block)
    promise.future.get(timeout)
  end

  def keyspace_changed(keyspace)
    @conditions.fetch(keyspace.name) {return}.each {|c| c.evaluate(keyspace)}
    nil
  end
end
```

**Comment by avalanche123** [comment]
more info about schema listeners can be found here http://datastax.github.io/ruby-driver/features/state_listeners/schema_changes/ and in the API docs http://datastax.github.io/ruby-driver/api/listener/ and

**Comment by stamhankar999** [comment]
Ooh, that looks neat. Will play with that now.

**Comment by avalanche123** [comment]
lgtm, just change the target branch to master

**Pull request closed without merging**
