### PR TITLE
Support for user defined types

### PR DESCRIPTION
**Pull request by iconara**
This is one of the things I had on my WIP but never got time to release in cql-rb. It adds support for encoding and decoding UDTs.

I'm not sure if this is the best implementation possible. I think UDTs in C* 2.1 felt pretty rushed, bolting it on using the custom types feature as it were. Because of this I had to implement a parser for the Thrift-style type definitions.

It looks like this is gone in v3 of the protocol, but that's not supported in C* 2.1, or have I missed that?

I'm not expecting you to merge this straight away, I just wanted to patch it up and see if it was even possible to get it to run in the new driver (it required very few changes, luckily).

### CODE REVIEW

**Comment by avalanche123** [comment]
this feature is coming soon and the work is happening in the [native-protocol-v3 branch](https://github.com/datastax/ruby-driver/tree/native-protocol-v3), closing this pull request, thanks for all your work.

**Comment by alex-klepa** [comment]
There's a bug in ruby driver. If you have UDT type collection map/list/set and already have some data, if you ALTER the type, you will get the error: *"Not enough bytes available to decode..."*


**How to replicate:**

```ruby
session.execute('CREATE TYPE address (street text, zipcode int)')
session.execute('CREATE TABLE users (id int PRIMARY KEY, location LIST<frozen<address>>)')
session.execute("INSERT INTO users (id, location) VALUES (0, [{street: '123 Main St.', zipcode: 78723}, {street: '4567 Main St.', zipcode: 87654}])")
session.execute('SELECT * FROM users')
session.execute('ALTER TYPE address ADD city text')
session.execute('SELECT * FROM users')
```

```
Cassandra::Errors::NoHostsAvailable: All attempted hosts failed: 127.0.0.1 (Cassandra::Errors::IOError: Not enough bytes available to decode an int: 4 bytes required to read an int, but only 0 available)
from /Users/alex/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cassandra-driver-2.1.5/lib/cassandra/future.rb:570:in `get'
```

**Comment by avalanche123** [comment]
please use JIRA for reporting bugs

**Comment by avalanche123** [comment]
indeed, I'm able to reproduce this issue

**Comment by avalanche123** [comment]
fixed in 4f1f19a16ef78a609a5ed3301c347f3cdd7be83c

**Comment by alex-klepa** [comment]
Great, thank you!

P.S. Couldn't find JIRA, that's why I reported it here, next time I find a bug I will.

**Pull request closed without merging**
